#!/bin/sh

BASENAME=$(which basename)
DATE=$(which date)
ECHO=/bin/echo

progname=$(${BASENAME} ${0})

if [ $# -ne 1 ]
then
	${ECHO} "usage: ${progname} <unix_timestamp>" >&2
	exit 1
fi

day=${1}
time=${2}
tz=${3}

# On a Mac, the -j argument to date may also be needed
# (why, I can't recall now)
# I don't yet know how to detect for that automatically and it's
# not worth my time right now
${DATE} -f "%s" ${1} "+%Y-%m-%d %H:%M:%S %Z"
