#!/bin/bash

progname=$(basename $0)

for arg in "$@"
do
	# Exclude arguments that turn out to not be directories
	if [ ! -d "${arg}" ]
	then
		echo "$progname: $arg: not a directory" >&2
		continue
	fi

	find "${arg}" -type d -and -name ".git" -print0 | xargs -0 -n 1 -I{} /bin/bash -c 'cd "{}/.." && pwd -P && git remote -v'
done
