#!/bin/bash

BASENAME=/bin/basename
ECHO=/bin/echo
GETOPT=/usr/bin/getopt
HEAD=/usr/bin/head
ID=/usr/bin/id
#LLQ=/usr/bin/llq
SQUEUE=/usr/bin/squeue
TAIL=/usr/bin/tail

progname=$(${BASENAME} ${0})
jobids_only="false"

# Execute getopt
ARGS=$(${GETOPT} -o iu: -l "jobids-only,user:" -n "${progname}" -- "$@");

#Bad arguments
if [ $? -ne 0 ];
then
	exit 1
fi

eval set -- "$ARGS";

while true
do
	case "$1" in
	-i|--jobids-only)
		shift;
		jobids_only="true"
		;;
	-u|--user)
		shift;
		if [ -n "$1" ]
		then
			user="$1"
			shift;
		fi
		;;
	--)
		shift;
		break;
		;;
	esac
done

me=$(${ID} -u -n)
if [ -z "${user}" ]
then
	user="${me}"
fi

#${ECHO} "------------------------------  LoadLeveler jobs  ------------------------------"
#llq -u ${user}
#${ECHO} ""
#${ECHO} "---------------------------------  Slurm jobs  ---------------------------------"
if [[ "${jobids_only}" == "true" ]]
then
	${SQUEUE} -o "%i" -u ${user} | ${TAIL} -n +2 | ${HEAD} -n -3
else
	${SQUEUE} -o "%.10i %.9P %.14j %.2t %.10M %.6D %R" -u ${user}
fi
