#!/bin/bash

BASENAME=/bin/basename
ECHO=/bin/echo
GETOPT=/usr/bin/getopt
HEAD=/usr/bin/head
ID=/usr/bin/id
#LLQ=/usr/bin/llq
TAIL=/usr/bin/tail

progname=$(${BASENAME} ${0})
jobids_only=false
wide=0

# Execute getopt
ARGS=$(${GETOPT} -o iu:w -l "jobids-only,user:,wide" -n "${progname}" -- "$@")

#Bad arguments
if [ $? -ne 0 ]
then
	exit 1
fi

eval set -- "$ARGS"

while true
do
	case "$1" in
	-i|--jobids-only)
		shift
		jobids_only=true
		;;
	-u|--user)
		shift
		if [ -n "$1" ]
		then
			user="$1"
			shift
		fi
		;;
	-w|--wide)
		shift
		wide=$((wide+1))
		;;
	--)
		shift
		break
		;;
	esac
done

if [[ "${wide}" -ne 0 && "${jobids_only}" == true ]]
then
	echo "Cannot print only job IDs in wide format."
	echo "You may use either -i or one or more -w options, but not both."
	exit 1
fi

me=$(${ID} -u -n)
if [ -z "${user}" ]
then
	user="${me}"
fi

if [ "${jobids_only}" = true ]
then
	squeue -o "%i" -u "${user}" | ${TAIL} -n +2 | ${HEAD} -n -3
else
	if [[ "${wide}" -eq 0 ]]
	then
		string="%.10i %.14j %.9P %.2t %.10M %.6D %R"
	elif [[ "${wide}" -eq 1 ]]
	then
		string="%.12i %.24j %.15a %.9P %.2t %.10M %.6D %R"
	else
		string="%.18i %.5Q %.9P %.8j %.8u %.8T %.10M %.11l %.6D %.4C %.6b %.20S %.20R %.8q"
	fi
	squeue -o "${string}" -u "${user}"
fi
